<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { api, ApiError, type Appointment, type Business, type Customer, type GoogleCalendarStatus, type Slot, type TelephonyStatus } from "./services/api";
import { messages, supportedLocale, type MessageKey } from "./i18n";

type Section = "overview" | "customers" | "availability" | "appointments";
type ConnectionState = "connected" | "needs-setup";
const section = ref<Section>("overview");
const business = ref<Business>(); const apiOnline = ref(false);
const googleCalendar = ref<GoogleCalendarStatus>({ configured: false, connected: false });
const telephony = ref<TelephonyStatus>({ configured: false, provider: "not-connected" });
const calendarNeedsReconnect = ref(new URLSearchParams(window.location.search).get("calendar") === "failed");
const globalError = ref(""); const busy = ref(false);
const customerForm = ref({ name: "", phone: "+52999" }); const customer = ref<Customer>();
const serviceId = ref(""); const employeeId = ref(""); const date = ref(nextWeekday());
const slots = ref<Slot[]>([]); const selectedSlot = ref<Slot>(); const createdAppointment = ref<Appointment>();
const lookupId = ref(""); const lookupResult = ref<Appointment>();
const selectedService = computed(() => business.value?.services.find((service) => service.id === serviceId.value));
const eligibleEmployees = computed(() => business.value?.employees.filter((employee) => selectedService.value?.eligibleEmployeeIds.includes(employee.id)) ?? []);
const locale = computed(() => supportedLocale(business.value?.locale)); const copy = computed(() => messages[locale.value]);
const navItems = computed(() => [["overview", copy.value.overview, "⌂"], ["customers", copy.value.customers, "☺"], ["availability", copy.value.availability, "◷"], ["appointments", copy.value.appointments, "▣"]] as Array<[Section, string, string]>);
const phonePlaceholder = computed(() => locale.value === "en-US" ? "+15125550123" : "+529991234567"); const t = (key: MessageKey): string => copy.value[key];
const calendarState = computed<ConnectionState>(() => googleCalendar.value.connected ? "connected" : "needs-setup");
const phoneState = computed<ConnectionState>(() => telephony.value.configured && telephony.value.provider !== "not-connected" ? "connected" : "needs-setup");

onMounted(async () => { try { const [health, profile, calendarStatus, telephonyStatus] = await Promise.all([api.health(), api.business(), api.googleCalendarStatus(), api.telephonyStatus()]); apiOnline.value = health.status === "ok"; business.value = profile; googleCalendar.value = calendarStatus; telephony.value = telephonyStatus; serviceId.value = profile.services[0]?.id ?? ""; employeeId.value = profile.services[0]?.eligibleEmployeeIds[0] ?? ""; customerForm.value.phone = profile.region === "US" ? "+1" : "+52"; } catch (error) { globalError.value = messageFor(error); } });
function chooseSection(value: Section): void { section.value = value; globalError.value = ""; }
async function connectGoogleCalendar(): Promise<void> { await run(async () => { window.location.assign((await api.googleCalendarConnect(window.location.origin)).url); }); }
function onServiceChanged(): void { employeeId.value = selectedService.value?.eligibleEmployeeIds[0] ?? ""; slots.value = []; selectedSlot.value = undefined; }
async function saveCustomer(): Promise<void> { await run(async () => { customer.value = await api.findOrCreateCustomer(customerForm.value); section.value = "availability"; }); }
async function checkAvailability(): Promise<void> { if (!serviceId.value || !employeeId.value || !date.value) return; await run(async () => { const rangeStart = `${date.value}T00:00:00.000Z`; const next = new Date(`${date.value}T00:00:00.000Z`); next.setUTCDate(next.getUTCDate() + 1); slots.value = (await api.availability({ serviceId: serviceId.value, employeeId: employeeId.value, rangeStart, rangeEnd: next.toISOString() })).slots; selectedSlot.value = undefined; }); }
async function createAppointment(): Promise<void> { if (!customer.value || !selectedSlot.value) return; await run(async () => { createdAppointment.value = await api.createAppointment({ customerId: customer.value!.id, serviceId: serviceId.value, employeeId: selectedSlot.value!.employeeId, startAt: selectedSlot.value!.startAt }); lookupId.value = createdAppointment.value.id; await checkAvailability(); section.value = "appointments"; }); }
async function findAppointment(): Promise<void> { if (!lookupId.value.trim()) return; await run(async () => { lookupResult.value = await api.appointment(lookupId.value.trim()); }); }
async function run(action: () => Promise<void>): Promise<void> { busy.value = true; globalError.value = ""; try { await action(); } catch (error) { globalError.value = messageFor(error); } finally { busy.value = false; } }
function messageFor(error: unknown): string { return error instanceof ApiError ? `${t("operationFailed")} (${error.code}).` : t("apiConnectionFailed"); }
function formatDateTime(value: string): string { return new Intl.DateTimeFormat(locale.value, { timeZone: business.value?.timezone ?? "America/Merida", dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function slotTime(value: string): string { return new Intl.DateTimeFormat(locale.value, { timeZone: business.value?.timezone ?? "America/Merida", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function nextWeekday(): string { const value = new Date(); value.setDate(value.getDate() + 1); while (value.getDay() === 0 || value.getDay() === 6) value.setDate(value.getDate() + 1); return value.toISOString().slice(0, 10); }
function statusLabel(status: string): string { if (status === "CONFIRMED") return locale.value === "en-US" ? "Confirmed" : "Confirmada"; if (status === "CANCELLED") return locale.value === "en-US" ? "Cancelled" : "Cancelada"; if (status === "FAILED") return locale.value === "en-US" ? "Failed" : "Fallida"; return status === "PENDING_CONFIRMATION" ? (locale.value === "en-US" ? "Pending confirmation" : "Pendiente de confirmación") : status; }
</script>

<template>
  <div class="shell">
    <aside class="sidebar">
      <button class="brand" type="button" aria-label="Go to overview" @click="chooseSection('overview')"><span class="brand-mark">Y</span><span><strong>YIBO</strong><small>Your AI receptionist</small></span></button>
      <nav aria-label="Main navigation"><button v-for="item in navItems" :key="item[0]" :class="{ active: section === item[0] }" @click="chooseSection(item[0])"><span class="nav-icon" aria-hidden="true">{{ item[2] }}</span>{{ item[1] }}</button></nav>
      <div class="sidebar-status"><span :class="['status-dot', { online: apiOnline }]"></span><span>{{ apiOnline ? 'YIBO is online' : 'Trying to connect' }}</span></div>
    </aside>
    <main>
      <header><div><p class="eyebrow">Your workspace</p><h1>{{ business?.name ?? 'YIBO Demo Clinic' }}</h1><p class="header-help">A simple place to manage your AI receptionist.</p></div><span class="timezone">{{ business?.timezone ?? 'America/Merida' }}</span></header>
      <p v-if="globalError" class="alert" role="alert">{{ globalError }}</p>
      <section v-if="section === 'overview'" class="view page-enter">
        <div class="hero-card"><div><span class="hero-icon">✦</span><p class="eyebrow">Reception desk status</p><h2>{{ apiOnline ? 'Your AI receptionist is ready' : 'Getting YIBO ready' }}</h2><p>{{ apiOnline ? 'Your dashboard is connected. Complete any cards below marked “Needs setup” to prepare for real calls.' : 'We are checking the connection to your local YIBO service.' }}</p></div><div class="hero-status"><span :class="['status-dot', { online: apiOnline }]"></span><strong>{{ apiOnline ? 'System online' : 'Checking' }}</strong></div></div>
        <div class="connection-grid">
          <article class="connection-card" :class="calendarState"><div class="connection-icon calendar">▣</div><div><span class="card-kicker">Calendar</span><h3>Google Calendar</h3><p>{{ googleCalendar.connected ? 'Appointments will be added to your connected calendar.' : googleCalendar.configured ? 'Connect your Google Calendar before making real bookings.' : 'Add your Google Calendar details to your local setup file.' }}</p></div><div class="card-footer"><span :class="['connection-badge', calendarState]"><i></i>{{ googleCalendar.connected ? 'Connected' : 'Needs setup' }}</span><button v-if="googleCalendar.configured && !googleCalendar.connected" class="secondary" :disabled="busy" @click="connectGoogleCalendar">{{ calendarNeedsReconnect ? 'Reconnect Calendar' : 'Connect Calendar' }}</button><span v-else-if="googleCalendar.connected" class="connected-check">✓</span></div></article>
          <article class="connection-card" :class="phoneState"><div class="connection-icon phone">☎</div><div><span class="card-kicker">Phone</span><h3>Phone system</h3><p>{{ phoneState === 'connected' ? 'Your phone system is ready to receive calls.' : 'Connect Asterisk and a phone number to receive real customer calls.' }}</p></div><div class="card-footer"><span :class="['connection-badge', phoneState]"><i></i>{{ phoneState === 'connected' ? 'Connected' : 'Needs setup' }}</span><span v-if="phoneState !== 'connected'" class="setup-hint">Setup required</span></div></article>
          <article class="connection-card needs-setup"><div class="connection-icon voice">✦</div><div><span class="card-kicker">AI voice</span><h3>AI receptionist</h3><p>AI voice will be ready after a voice provider is connected to your phone system.</p></div><div class="card-footer"><span class="connection-badge needs-setup"><i></i>Needs setup</span><span class="setup-hint">Voice provider required</span></div></article>
          <article class="connection-card appointments"><div class="connection-icon appointment">◷</div><div><span class="card-kicker">Appointments</span><h3>{{ createdAppointment ? 'Recent booking saved' : 'Ready for bookings' }}</h3><p>{{ createdAppointment ? formatDateTime(createdAppointment.startAt) : 'Create a customer and choose an available time to make your first appointment.' }}</p></div><div class="card-footer"><button class="text-button" @click="chooseSection(createdAppointment ? 'appointments' : 'customers')">{{ createdAppointment ? 'View appointment →' : 'Start a booking →' }}</button></div></article>
        </div>
        <div class="two-column overview-details"><article class="panel gentle-card"><div class="panel-heading"><div><p class="eyebrow">Today at a glance</p><h3>Recent activity</h3></div><span class="soft-icon">☼</span></div><div v-if="createdAppointment" class="activity-row"><span class="activity-icon">✓</span><div><strong>Appointment confirmed</strong><small>{{ formatDateTime(createdAppointment.startAt) }}</small></div></div><div v-else class="friendly-empty"><span>☁</span><strong>No activity yet</strong><p>When YIBO books an appointment or handles a call, you’ll see it here.</p></div></article><article class="panel gentle-card"><div class="panel-heading"><div><p class="eyebrow">Clinic details</p><h3>What YIBO knows</h3></div><span class="soft-icon">♡</span></div><div class="mini-stats"><div><strong>{{ business?.services.length ?? '—' }}</strong><span>Services</span></div><div><strong>{{ business?.employees.length ?? '—' }}</strong><span>Team members</span></div><div><strong>{{ business?.timezone ?? '—' }}</strong><span>Time zone</span></div></div></article></div>
      </section>
      <section v-else-if="section === 'customers'" class="view narrow page-enter"><div class="section-heading"><div><p class="eyebrow">Customers</p><h2>Find or create a customer</h2><p>Start with their phone number. We’ll find an existing record or create a new one.</p></div></div><form class="panel form-card" @submit.prevent="saveCustomer"><label>{{ t('name') }} <span>Optional</span><input v-model="customerForm.name" autocomplete="name" :placeholder="t('namePlaceholder')" /></label><label>{{ t('phone') }}<input v-model="customerForm.phone" required autocomplete="tel" :placeholder="phonePlaceholder" /></label><button class="primary" :disabled="busy">{{ busy ? t('processing') : 'Continue to availability →' }}</button></form><article v-if="customer" class="result-card success-card"><span class="result-label">Customer ready</span><h3>{{ customer.name || t('unnamed') }}</h3><p>{{ customer.phone }}</p><button class="text-button" @click="chooseSection('availability')">Find an appointment time →</button></article></section>
      <section v-else-if="section === 'availability'" class="view page-enter"><div class="section-heading"><div><p class="eyebrow">Appointments</p><h2>Find an available time</h2><p>Choose a service, team member, and date. All times are shown in {{ business?.timezone }}.</p></div><span v-if="customer" class="soft-pill">For {{ customer.name || customer.phone }}</span></div><div class="panel filters"><label>{{ t('service') }}<select v-model="serviceId" @change="onServiceChanged"><option v-for="service in business?.services" :key="service.id" :value="service.id">{{ service.name }} · {{ service.durationMinutes }} min</option></select></label><label>{{ t('professional') }}<select v-model="employeeId"><option v-for="employee in eligibleEmployees" :key="employee.id" :value="employee.id">{{ employee.displayName }}</option></select></label><label>{{ t('date') }}<input v-model="date" type="date" /></label><button class="primary" :disabled="busy" @click="checkAvailability">{{ busy ? 'Searching…' : 'Find times' }}</button></div><div v-if="slots.length" class="slots"><button v-for="slot in slots" :key="`${slot.employeeId}-${slot.startAt}`" :class="['slot', { selected: selectedSlot?.startAt === slot.startAt }]" @click="selectedSlot = slot"><strong>{{ slotTime(slot.startAt) }}</strong><small>until {{ slotTime(slot.endAt) }}</small></button></div><div v-else class="empty"><span class="empty-icon">◷</span><strong>Choose your filters, then find times</strong><span>Available appointment times will appear here.</span></div><div v-if="selectedSlot" class="booking-bar"><div><span>Selected time</span><strong>{{ formatDateTime(selectedSlot.startAt) }}</strong></div><button class="primary" :disabled="!customer || busy" @click="createAppointment">{{ customer ? 'Book this appointment' : 'Create customer first' }}</button></div></section>
      <section v-else class="view page-enter"><div class="section-heading"><div><p class="eyebrow">Appointments</p><h2>Appointment details</h2><p>Look up a booking by its appointment ID.</p></div></div><article v-if="createdAppointment" class="result-card success-card featured"><span class="result-label">Appointment confirmed ✓</span><h3>{{ formatDateTime(createdAppointment.startAt) }}</h3><p>Your customer’s appointment is saved{{ createdAppointment.externalCalendarEventId ? ' and added to Google Calendar.' : '.' }}</p><div class="appointment-summary"><span>{{ statusLabel(createdAppointment.status) }}</span><span>{{ createdAppointment.id }}</span></div></article><form class="panel lookup" @submit.prevent="findAppointment"><label>{{ t('appointmentId') }}<input v-model="lookupId" placeholder="appointment-1" /></label><button class="primary" :disabled="busy">{{ busy ? 'Looking…' : 'Find appointment' }}</button></form><article v-if="lookupResult" class="panel details"><div><span>ID</span><strong>{{ lookupResult.id }}</strong></div><div><span>{{ t('customer') }}</span><strong>{{ lookupResult.customerId }}</strong></div><div><span>{{ t('service') }}</span><strong>{{ lookupResult.serviceId }}</strong></div><div><span>{{ t('professional') }}</span><strong>{{ lookupResult.employeeId }}</strong></div><div><span>{{ t('start') }}</span><strong>{{ formatDateTime(lookupResult.startAt) }}</strong></div><div><span>{{ t('status') }}</span><strong>{{ statusLabel(lookupResult.status) }}</strong></div></article><div v-if="!createdAppointment && !lookupResult" class="empty"><span class="empty-icon">♡</span><strong>No appointment selected</strong><span>New bookings and appointment details will appear here.</span></div></section>
    </main>
  </div>
</template>
